apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
spec:
  template:
    spec:
      containers:
        - name: echoserver
          env:
          - name: DEBUG
            value: true
